### ISSUE TITLE
Doesn't work with 0.86 version

### ISSUE THREAD

**Issue by zacaruca** [Miicroo/homeassistant-custom-components#1]
This is the error:
ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 336, in _async_add_entity
    'Invalid entity id: {}'.format(entity.entity_id))
homeassistant.exceptions.HomeAssistantError: Invalid entity id: birthday.Javi

Can you help me? Thanks

**Comment by Miicroo** [comment]
@zacaruca Pushed a fix yesterday and verified that it was working (though I might be one minor version behind latest HA). If you use name _Javi_ your entity will get id  _birthday.javi_. Thanks for reporting the issue!
